name: My Gatsby Github Page Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: enriikke/gatsby-gh-pages-action@v2.2.0
        with:
          access-token: ${{ secrets.MY_GATSBY_GITHUB_PAGE_DEPLOYMENT }}
          deploy-branch: deployment
